### PR TITLE
Add steps for windows build

### PR DESCRIPTION
**Pull request by JAicewizard**

### CODE REVIEW

**Comment by JAicewizard** [comment]
I am genuinely not sure why github thinks there are over 250 commits here. This is my `git log`:

```
commit 24bff14543872826dcc361282635237c90b342f7 (HEAD -> windows, origin/windows)
Author: Jaap Aarts <jaap.aarts1@gmail.com>
Date:   Sun Oct 27 15:37:12 2024 +0100

    Add instructions on how to compile on windows

commit 323b3a97ce6497bd6041157c221cee86de113376
Author: Jaap Aarts <jaap.aarts1@gmail.com>
Date:   Sun Oct 27 13:46:50 2024 +0100

    Log gcc version

commit 7c41608848a85c7925c5123d50f3cc62deb43037 (origin/main, origin/HEAD, main)
Merge: ba0eeb8 b646fbd
Author: tania <44262898+taniabogatsch@users.noreply.github.com>
Date:   Wed Oct 16 09:48:15 2024 +0200

    Merge pull request #201 from JAicewizard/main

    Table function UDFs
...
```

**Comment by JAicewizard** [comment]
nvm found the issue

**Comment by JAicewizard** [comment]
@yusufozturk if you could check if this works for you?

**Comment by yusufozturk** [comment]
Wow thanks @JAicewizard I will check it asap.

**Review by taniabogatsch — COMMENTED** [review]
Thanks a lot for looking into this and expanding the `README`! Could you remove the binaries? I think the `Makefile` changes triggered a rebuild on your fork.

Otherwise, once @yusufozturk confirms that this works, we can merge it!

**Comment by JAicewizard** [comment]
I can but I think CI will just add them again, at least it did before. Any way to prevent CI from building them?

**Comment by taniabogatsch** [comment]
Thanks!

**Pull request merged**
